name: Run Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        numpy-version: ["1.26.4","2.1.3", "2.2.6"]

    name: Python ${{ matrix.python-version }} / NumPy ${{ matrix.numpy-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy==${{ matrix.numpy-version }}
        pip install -e .

    - name: Run tests
      run: pytest

